[tool.poetry]
name = "kursovay-oop-hh"
version = "0.1.0"
description = ""
authors = ["Olonov Aleksandr <adrolv08111985@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.13.*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
